"""Freeze and preflight the covered 18-cell Ab2d-Assembly v3 rerun; no calls."""
from __future__ import annotations
import hashlib,json,inspect,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from agent_tools.finals_rebuild.ce115_ab2d_assembly import TASK_API_MAPPING,stub_for_task,runtime_smoke,scan_assembly
M=ROOT/'docs/experiments/manifests';R=ROOT/'docs/experiments/results'
TASKS=[k for k,v in TASK_API_MAPPING.items() if not v.get('coverage')];MODELS=['qwen3.5:4b','qwen3.5:9b'];SEEDS=[2026071301,2026071302,2026071303]
def sha(b):return hashlib.sha256(b if isinstance(b,bytes) else b.encode()).hexdigest()
def main():
 cells=[{'cell_id':f"{m.replace('.','_').replace(':','_')}__{t}__ab2d_assembly_v3__seed_{s}",'model':m,'task':t,'seed':s,'condition':'ab2d_assembly_v3','run_id':'ce115_ab2d_assembly_v3_formal_rerun','retry':0,'healer':0,'repair':0,'replay':0,'output_path':f'docs/experiments/results/ce115_ab2d_assembly_v3_formal_rerun/{m.replace(".","_").replace(":","_")}__{t}__seed_{s}.json'} for m in MODELS for t in TASKS for s in SEEDS]
 exclusions=[{'model':m,'task':'ce115_calc_polynomial_factor_roots_l1','seed':s,'classification':'STRUCTURAL_EXCLUSION_ASSEMBLY_COVERAGE_UNAVAILABLE'} for m in MODELS for s in SEEDS]
 hashes={'mapping':sha(json.dumps(TASK_API_MAPPING,sort_keys=True)),'prompts':{t:sha(stub_for_task(t)) for t in TASKS},'scanner':sha(inspect.getsource(scan_assembly)),'evaluator':sha((ROOT/'scripts/forensics_ce115_ab2d_runtime_assembly.py').read_bytes()),'canonical_library':sha((ROOT/'core/prompts/domain_function_library.py').read_bytes()),'runner':sha((ROOT/'scripts/run_ce115_ab2d_polydiv_contract_smoke.py').read_bytes()),'artifact_schema':sha(json.dumps(sorted(['run_id','cell_id','model','task','seed','complete_payload','prompt_hash','payload_hash','raw_output','raw_output_hash','scanner','runtime_result','exact_evaluator_result','final_taxonomy','telemetry','wall_clock_seconds','exception_detail'] )))}
 protocol={'protocol_id':'ce115_ab2d_assembly_protocol_v3','freeze_status':'FROZEN','source_commit':'7494a678','hashes':hashes,'models':MODELS,'covered_tasks':TASKS,'seeds':SEEDS,'generation':{'num_ctx':65536,'num_predict':24576,'think':False,'temperature':0.0,'first_attempt_only':True,'retry':0,'healer':0,'repair':0,'replay':0},'planned_cells':18,'structural_exclusions':exclusions};protocol['hashes']['protocol']=sha(json.dumps(protocol,sort_keys=True))
 M.mkdir(parents=True,exist_ok=True);(M/'ce115_ab2d_assembly_protocol_v3.json').write_text(json.dumps(protocol,indent=2)+'\n');(M/'ce115_ab2d_assembly_protocol_v3.md').write_text('# CE115 Ab2d Assembly protocol v3\n\nFROZEN covered-task protocol; 18-cell rerun is planned, not executed.\n')
 manifest={'run_id':'ce115_ab2d_assembly_v3_formal_rerun','protocol_hash':protocol['hashes']['protocol'],'cells':cells,'exclusions':exclusions,'resume':False,'no_overwrite':True,'model_calls_planned':18};(M/'ce115_ab2d_corrected_formal_rerun_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
 active={'ACTIVE_DEFECT':[],'SAFE_TEST_NEGATIVE_CASE':['nested coefficient list','scalar/float remainder','malformed fraction/radical','extra/missing key','wrong oracle','parse/execution error'],'LEGACY_NONCANONICAL':[],'DOCUMENTATION_ONLY':[]};(R/'ce115_ab2d_active_defect_scan.json').write_text(json.dumps(active,indent=2)+'\n')
 sources={'ce115_calc_polynomial_division_l1':'def generate(level=1,**k):\n quotient_coefficients,remainder_coefficients=PolynomialOps.div_qr([-6,-4,3],[1,-2]);return {"question_text":"q","correct_answer":{"quotient_coefficients":quotient_coefficients,"remainder_coefficients":remainder_coefficients},"oracle_payload":{}}\n','ce115_calc_exact_rational_expression_l1':'def generate(level=1,**k):\n a=FractionOps.create("1/2");b=FractionOps.create("1/3");FractionOps.sub(FractionOps.div(FractionOps.mul(FractionOps.add(a,b),a),b),a);return {"question_text":"q","correct_answer":{},"oracle_payload":{}}\n','ce115_calc_radical_simplification_l1':'def generate(level=1,**k):\n e=RadicalLogicEngine();c,r=RadicalOps.simplify_term(1,12);RadicalOps.format_expression({r:c});return {"question_text":"q","correct_answer":{},"oracle_payload":{}}\n'}
 synthetic={t:runtime_smoke(src,t) for t,src in sources.items()};(R/'ce115_ab2d_synthetic_3task_validation.json').write_text(json.dumps(synthetic,indent=2)+'\n')
 telemetry={'required_fields':['prompt_eval_count','eval_count','total_duration','load_duration','prompt_eval_duration','eval_duration','wall_clock_seconds'],'null_policy':'null means unavailable; never coerce to zero','schema_complete':True};(R/'ce115_ab2d_telemetry_schema_validation.json').write_text(json.dumps(telemetry,indent=2)+'\n')
 blockers=[]
 if len(cells)!=18 or len({c['cell_id'] for c in cells})!=18:blockers.append('cell geometry')
 if active['ACTIVE_DEFECT']:blockers.append('active defect')
 if not all(v['classification']=='ASSEMBLY_COMPLIANT' for v in synthetic.values()):blockers.append('synthetic')
 result={'verdict':'FORMAL_RERUN_PREFLIGHT_BLOCKED' if blockers else 'FORMAL_RERUN_PREFLIGHT_READY','blocking_reasons':blockers,'freeze_status':'FROZEN','protocol_hash':protocol['hashes']['protocol'],'planned_cells':18,'roots_exclusions':6,'model_healer_repair_replay_retry_calls':0};(R/'ce115_ab2d_protocol_v3_preflight.json').write_text(json.dumps(result,indent=2)+'\n');(R/'ce115_ab2d_protocol_v3_preflight.md').write_text('# Protocol v3 preflight\n\n```json\n'+json.dumps(result,indent=2)+'\n```\n')
if __name__=='__main__':main()
